FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM nginx:alpine3.24

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/upload-file-example/browser /usr/share/nginx/html

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]
